# Generated by Django 3.1.6 on 2021-03-01 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('imdb_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('genre', models.TextField()),
                ('duration', models.IntegerField()),
                ('country', models.CharField(max_length=30)),
                ('director', models.CharField(max_length=50)),
                ('production_company', models.CharField(max_length=50)),
                ('actors', models.TextField()),
                ('description', models.TextField()),
                ('imdb_url', models.TextField()),
                ('poster_url', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SavedMovie',
            fields=[
                ('saved_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('movie_imdb_id', models.CharField(max_length=20)),
                ('date_added', models.DateTimeField()),
            ],
        ),
    ]
