# Generated by Django 3.1.6 on 2021-02-13 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imdb_id', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('genre', models.TextField()),
                ('duration', models.IntegerField()),
                ('country', models.CharField(max_length=30)),
                ('director', models.CharField(max_length=50)),
                ('production_company', models.CharField(max_length=50)),
                ('actors', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
    ]
