# Generated by Django 3.1.6 on 2021-03-01 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='recommendations',
            field=models.TextField(default='default'),
            preserve_default=False,
        ),
    ]
