# Generated by Django 3.1.6 on 2021-02-17 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='movie_list',
            field=models.TextField(null=True),
        ),
    ]
